/*
  シール素材の いちらん
  ------------------------------------------------------------
  あたらしい シールを ふやす ときは：
    1. 画像（PNG・背景は透明・正方形・256px くらい）を この stickers フォルダに 入れる
    2. 下の リストの「いちばん さいご」に 1行 たす
         { id: "ファイル名と同じ英数字", name: "シールの なまえ（ひらがな）", file: "ファイル名.png" },
  ※ id は 一度 きめたら かえない（もらった シールの きろくに つかう ため）
  ※ 行の 順番も かえない・けさない（いちばん さいごに たすだけ）
  ※ まるい シール（背景つきの まる）は round: true を つけると、まる いっぱいに 大きく 表示される
  ※ もう ださない シールは 行を けさずに retired: true を つける（もらった シールは そのまま のこる）
*/
window.STICKERS = [
  { id: "nikukyu",    name: "にくきゅう",   file: "nikukyu.png", round: true, retired: true },
  { id: "hoshi2",     name: "きらきらぼし", file: "hoshi2.png", round: true, retired: true },
  { id: "onpu",       name: "おんぷ",       file: "onpu.png", round: true },
  { id: "heart2",     name: "ハート",       file: "heart2.png", round: true, retired: true },
  { id: "mii",        name: "みー",         file: "mii.png", round: true },
  { id: "koro",       name: "ころ",         file: "koro.png", round: true },
  { id: "enpitsu",    name: "えんぴつ",     file: "enpitsu.png", round: true, retired: true },
  { id: "hon",        name: "ほん",         file: "hon.png", round: true, retired: true },
  { id: "medal",      name: "メダル",       file: "medal.png", round: true, retired: true },
  { id: "niji",       name: "にじ",         file: "niji.png", round: true, retired: true },
  { id: "taiyou2",    name: "おひさま",     file: "taiyou2.png", round: true, retired: true },
  { id: "ouchi",      name: "おうち",       file: "ouchi.png", round: true },
  { id: "yokudekita", name: "よくできたね", file: "yokudekita.png", round: true },
  { id: "nikoboshi",  name: "にこにこぼし", file: "nikoboshi.png", round: true },
  { id: "ashiato",    name: "あしあと",     file: "ashiato.png", round: true },
  { id: "oukan",      name: "おうかん",     file: "oukan.png", round: true, retired: true },
  { id: "futaba",     name: "ふたば",       file: "futaba.png", round: true },
  // ---- 2026-10-03 追加：まるい シール 30まい ----
  { id: "mii_yatta", name: "みー やったー", file: "mii_yatta.png", round: true },
  { id: "koro_nikkori", name: "ころ にっこり", file: "koro_nikkori.png", round: true },
  { id: "nakayoshi", name: "なかよし", file: "nakayoshi.png", round: true },
  { id: "mii_jump", name: "みー ジャンプ", file: "mii_jump.png", round: true },
  { id: "koro_jump", name: "ころ ジャンプ", file: "koro_jump.png", round: true },
  { id: "haitatchi", name: "ハイタッチ", file: "haitatchi.png", round: true },
  { id: "gyu", name: "ぎゅー", file: "gyu.png", round: true },
  { id: "benkyou", name: "いっしょに べんきょう", file: "benkyou.png", round: true },
  { id: "dokusho", name: "いっしょに どくしょ", file: "dokusho.png", round: true },
  { id: "banzai", name: "ばんざい", file: "banzai.png", round: true },
  { id: "hoshi3", name: "おおきな ほし", file: "hoshi3.png", round: true },
  { id: "kirakira", name: "きらきら", file: "kirakira.png", round: true },
  { id: "niji2", name: "にじ", file: "niji2.png", round: true },
  { id: "taiyou3", name: "にこにこ たいよう", file: "taiyou3.png", round: true },
  { id: "tsuki2", name: "おつきさま", file: "tsuki2.png", round: true },
  { id: "heart3", name: "ハート", file: "heart3.png", round: true },
  { id: "oukan2", name: "おうかん", file: "oukan2.png", round: true },
  { id: "kinmedal", name: "きんメダル", file: "kinmedal.png", round: true },
  { id: "takarabako", name: "たからばこ", file: "takarabako.png", round: true },
  { id: "present", name: "プレゼント", file: "present.png", round: true },
  { id: "juu", name: "10", file: "juu.png", round: true },
  { id: "nikukyu2", name: "にくきゅう", file: "nikukyu2.png", round: true },
  { id: "enpitsu2", name: "えんぴつ", file: "enpitsu2.png", round: true },
  { id: "nooto", name: "ノート", file: "nooto.png", round: true },
  { id: "honnoyama", name: "ほんの やま", file: "honnoyama.png", round: true },
  { id: "onetwothree", name: "123", file: "onetwothree.png", round: true },
  { id: "mii_tewofuru", name: "みー てを ふる", file: "mii_tewofuru.png", round: true },
  { id: "koro_tewofuru", name: "ころ てを ふる", file: "koro_tewofuru.png", round: true },
  { id: "futari_hoshi", name: "ふたりと ほし", file: "futari_hoshi.png", round: true },
  { id: "futari_yoru", name: "ふたりの よる", file: "futari_yoru.png", round: true },
  // ---- 2026-10-03 追加：どうぶつ シール 30まい ----
  { id: "a_neko", name: "ねこ", file: "a_neko.png", round: true },
  { id: "a_chatora", name: "ちゃとら", file: "a_chatora.png", round: true },
  { id: "a_suyasuya", name: "すやすや ねこ", file: "a_suyasuya.png", round: true },
  { id: "a_inu", name: "いぬ", file: "a_inu.png", round: true },
  { id: "a_shiba", name: "しばいぬ", file: "a_shiba.png", round: true },
  { id: "a_usagi", name: "うさぎ", file: "a_usagi.png", round: true },
  { id: "a_kuma", name: "くま", file: "a_kuma.png", round: true },
  { id: "a_panda", name: "パンダ", file: "a_panda.png", round: true },
  { id: "a_hamster", name: "ハムスター", file: "a_hamster.png", round: true },
  { id: "a_risu", name: "りす", file: "a_risu.png", round: true },
  { id: "a_lion", name: "ライオン", file: "a_lion.png", round: true },
  { id: "a_zou", name: "ぞう", file: "a_zou.png", round: true },
  { id: "a_kirin", name: "きりん", file: "a_kirin.png", round: true },
  { id: "a_shimauma", name: "しまうま", file: "a_shimauma.png", round: true },
  { id: "a_saru", name: "おさる", file: "a_saru.png", round: true },
  { id: "a_kitsune", name: "きつね", file: "a_kitsune.png", round: true },
  { id: "a_tanuki", name: "たぬき", file: "a_tanuki.png", round: true },
  { id: "a_ookami", name: "おおかみ", file: "a_ookami.png", round: true },
  { id: "a_lesserpanda", name: "レッサーパンダ", file: "a_lesserpanda.png", round: true },
  { id: "a_koala", name: "コアラ", file: "a_koala.png", round: true },
  { id: "a_penguin", name: "ペンギン", file: "a_penguin.png", round: true },
  { id: "a_azarashi", name: "あざらし", file: "a_azarashi.png", round: true },
  { id: "a_iruka", name: "いるか", file: "a_iruka.png", round: true },
  { id: "a_kujira", name: "くじら", file: "a_kujira.png", round: true },
  { id: "a_fukurou", name: "ふくろう", file: "a_fukurou.png", round: true },
  { id: "a_inko", name: "インコ", file: "a_inko.png", round: true },
  { id: "a_kame", name: "かめ", file: "a_kame.png", round: true },
  { id: "a_kaeru", name: "かえる", file: "a_kaeru.png", round: true },
  { id: "a_chou", name: "ちょうちょ", file: "a_chou.png", round: true },
  { id: "a_unicorn", name: "ユニコーン", file: "a_unicorn.png", round: true },
  // ---- 2026-10-03 追加：きょうりゅう シール 30まい ----
  { id: "d_tyranno", name: "ティラノサウルス", file: "d_tyranno.png", round: true },
  { id: "d_torikera", name: "トリケラトプス", file: "d_torikera.png", round: true },
  { id: "d_sutego", name: "ステゴサウルス", file: "d_sutego.png", round: true },
  { id: "d_pakike", name: "パキケファロサウルス", file: "d_pakike.png", round: true },
  { id: "d_ankiro", name: "アンキロサウルス", file: "d_ankiro.png", round: true },
  { id: "d_allo", name: "アロサウルス", file: "d_allo.png", round: true },
  { id: "d_spino", name: "スピノサウルス", file: "d_spino.png", round: true },
  { id: "d_brachio", name: "ブラキオサウルス", file: "d_brachio.png", round: true },
  { id: "d_ptera", name: "プテラノドン", file: "d_ptera.png", round: true },
  { id: "d_parasauro", name: "パラサウロロフス", file: "d_parasauro.png", round: true },
  { id: "d_apato", name: "アパトサウルス", file: "d_apato.png", round: true },
  { id: "d_tsuno", name: "つのの きょうりゅう", file: "d_tsuno.png", round: true },
  { id: "d_kamo", name: "カモノハシりゅう", file: "d_kamo.png", round: true },
  { id: "d_maia", name: "マイアサウラ", file: "d_maia.png", round: true },
  { id: "d_shisocho", name: "しそちょう", file: "d_shisocho.png", round: true },
  { id: "d_kazan", name: "かざんと きょうりゅう", file: "d_kazan.png", round: true },
  { id: "d_dimetro", name: "ディメトロドン", file: "d_dimetro.png", round: true },
  { id: "d_terijino", name: "テリジノサウルス", file: "d_terijino.png", round: true },
  { id: "d_hane", name: "はねの きょうりゅう", file: "d_hane.png", round: true },
  { id: "d_togetoge", name: "トゲトゲ きょうりゅう", file: "d_togetoge.png", round: true },
  { id: "d_velo", name: "ヴェロキラプトル", file: "d_velo.png", round: true },
  { id: "d_dilo", name: "ディロフォサウルス", file: "d_dilo.png", round: true },
  { id: "d_bary", name: "バリオニクス", file: "d_bary.png", round: true },
  { id: "d_osuwari", name: "おすわり きょうりゅう", file: "d_osuwari.png", round: true },
  { id: "d_raptor", name: "むらさき ラプトル", file: "d_raptor.png", round: true },
  { id: "d_chibisutego", name: "ちびステゴ", file: "d_chibisutego.png", round: true },
  { id: "d_compso", name: "コンプソグナトゥス", file: "d_compso.png", round: true },
  { id: "d_ovi", name: "オヴィラプトル", file: "d_ovi.png", round: true },
  { id: "d_midori", name: "みどり ラプトル", file: "d_midori.png", round: true },
  { id: "d_kubinaga", name: "くびながりゅう", file: "d_kubinaga.png", round: true },
  // ---- 2026-10-03 追加：うちゅう シール 27まい ----
  { id: "s_rocket", name: "ロケット", file: "s_rocket.png", round: true },
  { id: "s_hoshigumo", name: "ほしぐも", file: "s_hoshigumo.png", round: true },
  { id: "s_taiyou", name: "たいよう", file: "s_taiyou.png", round: true },
  { id: "s_ufo_alien", name: "UFOと うちゅうじん", file: "s_ufo_alien.png", round: true },
  { id: "s_station", name: "うちゅうステーション", file: "s_station.png", round: true },
  { id: "s_wakusei_pink", name: "ピンクの わくせい", file: "s_wakusei_pink.png", round: true },
  { id: "s_suisei", name: "すいせい", file: "s_suisei.png", round: true },
  { id: "s_bouenkyou", name: "ぼうえんきょう", file: "s_bouenkyou.png", round: true },
  { id: "s_wakusei_green", name: "みどりの わくせい", file: "s_wakusei_green.png", round: true },
  { id: "s_tansaki", name: "たんさき", file: "s_tansaki.png", round: true },
  { id: "s_oyasumi", name: "おやすみ おつきさま", file: "s_oyasumi.png", round: true },
  { id: "s_wakusei_blue", name: "あおい わくせい", file: "s_wakusei_blue.png", round: true },
  { id: "s_ginga", name: "ぎんが", file: "s_ginga.png", round: true },
  { id: "s_tansasha", name: "たんさしゃ", file: "s_tansasha.png", round: true },
  { id: "s_uchuneko", name: "うちゅうねこ", file: "s_uchuneko.png", round: true },
  { id: "s_astronaut", name: "うちゅうひこうし", file: "s_astronaut.png", round: true },
  { id: "s_shuttle", name: "スペースシャトル", file: "s_shuttle.png", round: true },
  { id: "s_eisei", name: "じんこうえいせい", file: "s_eisei.png", round: true },
  { id: "s_blackhole", name: "ブラックホール", file: "s_blackhole.png", round: true },
  { id: "s_hokuto", name: "ほくとしちせい", file: "s_hokuto.png", round: true },
  { id: "s_ufo_pink", name: "ピンクの UFO", file: "s_ufo_pink.png", round: true },
  { id: "s_nagareboshi", name: "ながれぼし", file: "s_nagareboshi.png", round: true },
  { id: "s_shouwakusei", name: "しょうわくせい", file: "s_shouwakusei.png", round: true },
  { id: "s_kichi", name: "うちゅうきち", file: "s_kichi.png", round: true },
  { id: "s_ufo_purple", name: "むらさきの UFO", file: "s_ufo_purple.png", round: true },
  { id: "s_alien", name: "うちゅうじん", file: "s_alien.png", round: true },
  { id: "s_dome", name: "つきの ドーム", file: "s_dome.png", round: true },
  // ---- 2026-10-03 追加：おはな シール 30まい ----
  { id: "f_bara", name: "ばら", file: "f_bara.png", round: true },
  { id: "f_wasurenagusa", name: "わすれなぐさ", file: "f_wasurenagusa.png", round: true },
  { id: "f_himawari", name: "ひまわり", file: "f_himawari.png", round: true },
  { id: "f_mebae", name: "めばえ", file: "f_mebae.png", round: true },
  { id: "f_lavender", name: "ラベンダー", file: "f_lavender.png", round: true },
  { id: "f_sakura", name: "さくら", file: "f_sakura.png", round: true },
  { id: "f_suiren", name: "すいれん", file: "f_suiren.png", round: true },
  { id: "f_tulip", name: "チューリップ", file: "f_tulip.png", round: true },
  { id: "f_clover", name: "よつばの クローバー", file: "f_clover.png", round: true },
  { id: "f_ran", name: "らん", file: "f_ran.png", round: true },
  { id: "f_botan", name: "ぼたん", file: "f_botan.png", round: true },
  { id: "f_daisy", name: "デイジー", file: "f_daisy.png", round: true },
  { id: "f_suisen", name: "すいせん", file: "f_suisen.png", round: true },
  { id: "f_shida", name: "しだ", file: "f_shida.png", round: true },
  { id: "f_sumire", name: "すみれ", file: "f_sumire.png", round: true },
  { id: "f_carnation", name: "カーネーション", file: "f_carnation.png", round: true },
  { id: "f_delphinium", name: "デルフィニウム", file: "f_delphinium.png", round: true },
  { id: "f_scoop", name: "はなと スコップ", file: "f_scoop.png", round: true },
  { id: "f_saboten", name: "サボテン", file: "f_saboten.png", round: true },
  { id: "f_ayame", name: "あやめ", file: "f_ayame.png", round: true },
  { id: "f_poppy", name: "ポピー", file: "f_poppy.png", round: true },
  { id: "f_tsurigane_blue", name: "あおい つりがねそう", file: "f_tsurigane_blue.png", round: true },
  { id: "f_tane", name: "たねと め", file: "f_tane.png", round: true },
  { id: "f_terrarium", name: "テラリウム", file: "f_terrarium.png", round: true },
  { id: "f_tsurigane_purple", name: "むらさきの つりがねそう", file: "f_tsurigane_purple.png", round: true },
  { id: "f_hasu", name: "はす", file: "f_hasu.png", round: true },
  { id: "f_kikyou", name: "ききょう", file: "f_kikyou.png", round: true },
  { id: "f_hanataba", name: "はなたば", file: "f_hanataba.png", round: true },
  { id: "f_ki", name: "き", file: "f_ki.png", round: true },
  { id: "f_murasaki", name: "むらさきの はな", file: "f_murasaki.png", round: true },
];
